import { readFileSync } from "node:fs";
import { dirname } from "node:path";
import type { ExtensionAPI, InputEvent, InputEventResult } from "@earendil-works/pi-coding-agent";

/**
 * Regex matching inline skill references: /skill:<name>
 * where name consists of alphanumeric characters, underscores, and hyphens.
 */
export const INLINE_SKILL_REGEX = /\/skill:([a-zA-Z0-9_-]+)/g;

/**
 * Strips YAML frontmatter from markdown file contents if present.
 */
export function stripFrontmatter(content: string): string {
  if (!content.startsWith("---")) return content;
  const match = content.match(/^---\r?\n[\s\S]*?\r?\n---\r?\n?/);
  if (match) {
    return content.slice(match[0].length);
  }
  return content;
}

export interface ResolvedSkill {
  name: string;
  filePath: string;
  baseDir?: string;
  content?: string;
}

export type SkillResolver = (
  name: string
) => ResolvedSkill | null | Promise<ResolvedSkill | null>;

export interface InterceptorOptions {
  enabled?: boolean;
  resolveSkill?: SkillResolver;
}

/**
 * Default resolver that inspects available slash commands and skills from ExtensionAPI.
 */
export function createDefaultSkillResolver(pi: ExtensionAPI): SkillResolver {
  return (name: string): ResolvedSkill | null => {
    try {
      const commands = pi.getCommands();
      const target = commands.find(
        (cmd) =>
          (cmd.source === "skill" || cmd.name.startsWith("skill:")) &&
          (cmd.name === `skill:${name}` || cmd.name === name)
      );

      if (!target || !target.sourceInfo?.path) {
        return null;
      }

      const filePath = target.sourceInfo.path;
      const baseDir = target.sourceInfo.baseDir || dirname(filePath);
      const content = readFileSync(filePath, "utf-8");

      return {
        name,
        filePath,
        baseDir,
        content,
      };
    } catch {
      // Gracefully handle file read errors or missing paths without interrupting
      return null;
    }
  };
}

/**
 * Transforms prompt text by finding inline /skill:<name> tokens, resolving skills,
 * deduplicating them, and prepending <skill>...</skill> blocks to the beginning of the prompt.
 *
 * Returns null if disabled or if no skills could be resolved.
 */
export async function transformPromptWithSkills(
  text: string,
  resolveSkill: SkillResolver,
  options?: { enabled?: boolean }
): Promise<string | null> {
  if (options?.enabled === false) {
    return null;
  }

  const matches = Array.from(text.matchAll(INLINE_SKILL_REGEX));
  if (matches.length === 0) {
    return null;
  }

  // Deduplicate unique skill names preserving appearance order
  const uniqueNames: string[] = [];
  for (const match of matches) {
    const name = match[1];
    if (name && !uniqueNames.includes(name)) {
      uniqueNames.push(name);
    }
  }

  const skillBlocks: string[] = [];

  for (const name of uniqueNames) {
    try {
      const skill = await resolveSkill(name);
      if (!skill) {
        // Unknown or unresolved skill; leave intact in text as plain text
        continue;
      }

      let rawContent = skill.content;
      if (rawContent === undefined && skill.filePath) {
        rawContent = readFileSync(skill.filePath, "utf-8");
      }

      if (rawContent === undefined) {
        continue;
      }

      const body = stripFrontmatter(rawContent).trim();
      const baseDir = skill.baseDir || dirname(skill.filePath);
      const block = `<skill name="${skill.name}" location="${skill.filePath}">\nReferences are relative to ${baseDir}.\n\n${body}\n</skill>`;
      skillBlocks.push(block);
    } catch {
      // Error tolerance: never let single skill failure disrupt submission
      continue;
    }
  }

  if (skillBlocks.length === 0) {
    return null;
  }

  // Prepend resolved skill blocks at the very top of the user prompt
  return `${skillBlocks.join("\n\n")}\n\n${text}`;
}

/**
 * Registers the input interceptor on the Pi extension.
 * Listens to pi.on("input", ...), ignores event.source === "extension",
 * and transforms prompts containing inline /skill:<name> tokens.
 */
export function registerInlineSkillInterceptor(
  pi: ExtensionAPI,
  options?: InterceptorOptions
): () => void {
  const resolver = options?.resolveSkill ?? createDefaultSkillResolver(pi);

  return pi.on("input", async (event: InputEvent): Promise<InputEventResult> => {
    // Ignore input events generated by extensions to avoid re-entrancy
    if (event.source === "extension") {
      return { action: "continue" };
    }

    // Check configuration flag (defaults to enabled)
    const flagEnabled = pi.getFlag ? pi.getFlag("inline-skills") : undefined;
    const isEnabled =
      options?.enabled !== false &&
      flagEnabled !== false &&
      flagEnabled !== "false";

    if (!isEnabled) {
      return { action: "continue" };
    }

    const transformed = await transformPromptWithSkills(event.text, resolver, {
      enabled: isEnabled,
    });

    if (transformed !== null) {
      return {
        action: "transform",
        text: transformed,
        images: event.images,
      };
    }

    return { action: "continue" };
  });
}
